package com.example.hms.payload.dto;

import com.example.hms.enums.PatientStayStatus;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Flat row behind the Hospital Registrations desk list.
 *
 * <p>Deliberately a column projection rather than an entity graph, for two
 * reasons.
 *
 * <p><b>It makes the LEFT JOINs mean what they say.</b>
 * {@code PatientHospitalRegistration.patient} is mapped {@code optional = false},
 * which tells Hibernate the target row is guaranteed to exist. The schema carries
 * no foreign keys at all — {@code V1__Initial_Schema.sql} was generated by
 * Hibernate's SchemaExport, which emits none — so that guarantee is not actually
 * enforced anywhere, and a registration whose {@code patient_id} points at a
 * deleted row is a reachable state. Fetch-joining such a row raises
 * {@code FetchNotFoundException} during result-set assembly instead of yielding
 * null, which returned a bare 500 for the WHOLE desk over a single orphan. That
 * throw happens inside the repository call, so no amount of defensive mapping
 * downstream can catch it. Selecting columns cannot fail that way: the orphan
 * simply arrives with null patient fields, which is what the desk wanted in the
 * first place.
 *
 * <p><b>It collapses the fetch.</b> The desk renders scalars only, but hydrating
 * the entities to reach them dragged in {@code Patient} → {@code User} →
 * ({@code userRoles} → {@code Role}, {@code patientProfile}, {@code staffProfile})
 * — the last two forced EAGER by {@code @NotFound} — for every row on the page.
 * That is roughly six statements per row and a blast radius wide enough that a
 * bad row anywhere inside it took down the list.
 *
 * <p>{@code active} is boxed on purpose. The column is {@code NOT NULL} today, but
 * a projection that unboxes straight into a primitive would turn any future
 * nullable-column migration into another whole-page 500; the mapper coalesces it.
 */
public record RegistrationDeskRow(
    UUID id,
    String mrn,

    UUID patientId,
    String patientUsername,
    String patientFirstName,
    String patientLastName,
    String patientEmail,
    String patientPhone,
    String patientGender,

    UUID hospitalId,
    String hospitalName,
    String hospitalCode,
    String hospitalAddress,

    LocalDate registrationDate,
    Boolean active,

    PatientStayStatus stayStatus,
    LocalDateTime stayStatusUpdatedAt,
    String currentRoom,
    String currentBed,
    String attendingPhysicianName,
    String readyForDischargeNote,
    UUID readyByStaffId
) {

    /** True when the registration's patient row could not be resolved (orphaned FK). */
    public boolean hasOrphanedPatient() {
        return patientId == null;
    }
}
