### HTTP request for creating a new user role hospital assignment
POST http://localhost:8081/api/audit-logs
Content-Type: application/json
Authorization: Bearer {{token}}
Accept-Language: en

{
  "userName": "Hospital Admin",
  "roleName": "Hospital Admin",
  "hospitalName": "Sandof Hospital",
  "eventType": "DATA_ACCESS",
  "eventDescription": "Patient record viewed",
  "details": "Viewed patient demographics.",
  "ipAddress": "192.168.0.101",
  "status": "SUCCESS",
  "resourceName": "Aicha Nana",
  "entityType": "PATIENT"
}

### Get audit logs by event type Only endpoints to only SUPER_ADMIN and HOSPITAL_ADMIN.
GET http://localhost:8081/api/audit-logs/event-type-status?eventType=DATA_ACCESS&page=0&size=20
Authorization: Bearer {{token}}
Accept: application/json

### Get audit logs by target
GET http://localhost:8081/api/audit-logs/target?entityType=USER&resourceId=e551120e-671f-4785-9ab8-59768c055f8e&page=0&size=20
Authorization: Bearer {{token}}
Accept: application/json


### Send invalid event type
POST http://localhost:8081/api/audit-logs
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userName": "Hospital Admin",
  "hospitalName": "Sandof Hospital",
  "eventType": "USER_UPDATE",
  "status": "SUCCESS",
  "entityType": "USER",
  "resourceName": "Aicha Nana"
}

### Missing required userId and eventType
POST http://localhost:8081/api/audit-logs
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "status": "SUCCESS"
}

### HTTP request for updating an existing audit log
GET http://localhost:8081/api/audit-logs/user/e551120e-671f-4785-9ab8-59768c055f8e?page=0&size=20
Authorization: Bearer {{token}}
Accept: application/json

### HTTP request for deleting an audit log
GET http://localhost:8081/api/audit-logs/event-type?eventType=LOGIN_SUCCESS&page=0&size=20
Authorization: Bearer {{token}}
Accept: application/json

### HTTP request for getting all audit logs
GET http://localhost:8081/api/audit-logs
Authorization: Bearer {{token}}
Accept: application/json

### HTTP request for getting audit logs by user ID
GET localhost:8081/api/audit-logs/target?entityType=PATIENT&resourceId=96cff0ec-7944-4ea8-b235-68bf32047205
Authorization: Bearer {{token}}
Accept: application/json
