### Create Permission (Super Admin only)
POST http://localhost:8081/api/permissions
Authorization: Bearer {{token}}
Content-Type: application/json
Accept-Language: en

{
  "name": "MANAGE_LAB_RESULTS",
  "assignmentId": "ac12859a-f858-4515-b576-c185de12b92c"
}

### Get Permission by ID
GET http://localhost:8081/api/permissions/ece20549-c3fa-4108-962a-cbacb6e24902
Authorization: Bearer {{token}}
Content-Type: application/json
Accept-Language: en

### Get All Permissions
GET http://localhost:8081/api/permissions
Authorization: Bearer {{token}}
Content-Type: application/json
Accept-Language: en

### Search Permissions by Assignment ID and Name
GET http://localhost:8081/api/permissions/search?assignmentId=ac12859a-f858-4515-b576-c185de12b92c&name=LAB&page=0&size=10
Authorization: Bearer {{token}}
Content-Type: application/json
Accept-Language: en

### Get Minimal Permissions
GET http://localhost:8081/api/permissions/minimal
Authorization: Bearer {{token}}
Content-Type: application/json
Accept-Language: en
