package com.example.hms.repository;

import com.example.hms.enums.OrganizationType;
import com.example.hms.enums.PatientStayStatus;
import com.example.hms.model.Hospital;
import com.example.hms.model.Organization;
import com.example.hms.model.Patient;
import com.example.hms.model.PatientHospitalRegistration;
import com.example.hms.model.User;
import com.example.hms.payload.dto.RegistrationDeskRow;
import com.example.hms.security.EncryptionKeyHolder;
import com.example.hms.security.tenant.TenantContextAccessor;
import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityNotFoundException;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;
import org.springframework.context.annotation.Import;
import org.springframework.test.context.ActiveProfiles;

import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * End-to-end DB test for the Hospital Registrations desk list.
 *
 * <p>Production incident: {@code GET /registrations?hospitalId=…} returned 500 for
 * every user with permission to register a patient. One registration row pointed
 * at a {@code patient_id} with no matching {@code clinical.patients} row, and
 * because {@code PatientHospitalRegistration.patient} is mapped
 * {@code optional = false}, fetch-joining it made Hibernate raise
 * {@code FetchNotFoundException} while assembling the result set instead of
 * yielding null. A single orphan took down the whole page, and the throw happened
 * inside the repository call, so the mapper's per-row guards never ran.
 *
 * <p><b>Why no existing test caught it.</b> The test profile runs H2 with
 * {@code ddl-auto: create-drop}, so Hibernate emits the {@code fk_phr_patient}
 * foreign key declared on the {@code @JoinColumn}. Production has no foreign keys
 * at all — {@code V1__Initial_Schema.sql} was generated by Hibernate's
 * SchemaExport, which emits none — so the integrity model under test was strictly
 * stronger than the one in production and an orphan was literally unrepresentable
 * here. These tests drop to {@code SET REFERENTIAL_INTEGRITY FALSE} to model the
 * database that actually runs.
 *
 * <p>That statement commits in H2, so the usual {@code @DataJpaTest} rollback does
 * not clean up after it. Hence the unique per-method fixture suffix and the
 * explicit teardown: without both, the first orphan row leaks into every later
 * test sharing this in-memory database.
 */
@DataJpaTest
@ActiveProfiles("test")
@Import({TenantContextAccessor.class, EncryptionKeyHolder.class})
class PatientHospitalRegistrationDeskRowIT {

    @Autowired private PatientHospitalRegistrationRepository repository;
    @Autowired private TestEntityManager em;

    private String uid;
    private Organization organization;
    private Hospital hospital;
    private Patient patient;
    private PatientHospitalRegistration registration;

    @BeforeEach
    void setUp() {
        uid = UUID.randomUUID().toString().substring(0, 8);

        organization = em.persist(Organization.builder()
            .name("Org " + uid)
            .code("ORG-" + uid)
            .type(OrganizationType.HOSPITAL_CHAIN)
            .build());

        hospital = em.persist(Hospital.builder()
            .name("Test Hospital")
            .code("HOSP-" + uid)
            .address("123 Test St")
            .city("Ouagadougou")
            .country("BF")
            .organization(organization)
            .build());

        patient = em.persist(newPatient("Awa", "Traore", "a" + uid));

        registration = em.persist(PatientHospitalRegistration.builder()
            .patient(patient)
            .hospital(hospital)
            .mrn("mrn-REG0001")
            .registrationDate(LocalDate.now())
            .active(true)
            .stayStatus(PatientStayStatus.ADMITTED)
            .currentRoom("204")
            .build());

        em.flush();
    }

    /**
     * Only the registrations need clearing. Every other fixture row carries this
     * method's unique suffix, so leaking one is harmless — but a leaked ORPHAN
     * registration is exactly the poison this class exists to test, and it would
     * follow the shared in-memory database into any later test that reads
     * registrations without a hospital filter.
     */
    @AfterEach
    void tearDown() {
        EntityManager e = em.getEntityManager();
        e.createNativeQuery("SET REFERENTIAL_INTEGRITY FALSE").executeUpdate();
        e.createNativeQuery("DELETE FROM clinical.patient_hospital_registrations WHERE hospital_id = :h")
            .setParameter("h", hospital.getId()).executeUpdate();
        e.createNativeQuery("SET REFERENTIAL_INTEGRITY TRUE").executeUpdate();
    }

    @Test
    void deskRows_healthyRow_carriesPatientAndHospitalDetail() {
        em.clear();

        List<RegistrationDeskRow> rows = repository.findDeskRowsByHospitalId(hospital.getId());

        assertThat(rows).hasSize(1);
        RegistrationDeskRow row = rows.get(0);
        assertThat(row.patientId()).isEqualTo(patient.getId());
        assertThat(row.patientUsername()).isEqualTo("a" + uid);
        assertThat(row.patientFirstName()).isEqualTo("Awa");
        assertThat(row.patientLastName()).isEqualTo("Traore");
        assertThat(row.hospitalName()).isEqualTo("Test Hospital");
        assertThat(row.mrn()).isEqualTo("mrn-REG0001");
        assertThat(row.currentRoom()).isEqualTo("204");
        assertThat(row.stayStatus()).isEqualTo(PatientStayStatus.ADMITTED);
        assertThat(row.active()).isTrue();
        assertThat(row.hasOrphanedPatient()).isFalse();
    }

    /**
     * The exact production shape: registration {@code b4dcaa91} referenced a
     * patient that no longer existed. Before the projection this threw and the
     * desk showed "Failed to load registrations" for everyone.
     */
    @Test
    void deskRows_orphanedPatientId_listsWithNullPatientInsteadOfThrowing() {
        orphanPatientReference(registration.getId());

        List<RegistrationDeskRow> rows = repository.findDeskRowsByHospitalId(hospital.getId());

        assertThat(rows)
            .as("an orphaned registration must still list — the desk is more useful "
                + "degraded than replaced by a 500")
            .hasSize(1);
        RegistrationDeskRow row = rows.get(0);
        assertThat(row.hasOrphanedPatient()).isTrue();
        assertThat(row.patientId()).isNull();
        assertThat(row.patientUsername()).isNull();
        assertThat(row.patientFirstName()).isNull();
        // Everything the registration itself owns still renders.
        assertThat(row.mrn()).isEqualTo("mrn-REG0001");
        assertThat(row.hospitalName()).isEqualTo("Test Hospital");
        assertThat(row.currentRoom()).isEqualTo("204");
    }

    /** One bad row must not remove the good ones from the page. */
    @Test
    void deskRows_orphanedRow_doesNotHideHealthyRows() {
        Patient other = em.persist(newPatient("Bintou", "Kone", "b" + uid));
        em.persist(PatientHospitalRegistration.builder()
            .patient(other)
            .hospital(hospital)
            .mrn("mrn-REG0002")
            .registrationDate(LocalDate.now())
            .active(true)
            .stayStatus(PatientStayStatus.ADMITTED)
            .build());
        em.flush();

        orphanPatientReference(registration.getId());

        List<RegistrationDeskRow> rows = repository.findDeskRowsByHospitalId(hospital.getId());

        assertThat(rows).hasSize(2);
        assertThat(rows).filteredOn(RegistrationDeskRow::hasOrphanedPatient).hasSize(1);
        assertThat(rows).extracting(RegistrationDeskRow::patientFirstName)
            .containsExactlyInAnyOrder(null, "Bintou");
    }

    /**
     * Proves the diagnosis instead of assuming it.
     *
     * <p>This is the exact query shape the repository used before — a fetch join
     * over the entity graph — run against the exact row that broke production. It
     * still throws, which is why the desk list projects columns now. If a future
     * change reintroduces a fetch join on this association, this is the failure it
     * will produce, and it will produce it for the whole page rather than one row.
     */
    @Test
    void fetchJoiningTheEntityGraph_stillThrowsOnTheSameOrphan() {
        orphanPatientReference(registration.getId());

        assertThatThrownBy(() -> em.getEntityManager().createQuery("""
                SELECT DISTINCT r FROM PatientHospitalRegistration r
                LEFT JOIN FETCH r.patient p
                LEFT JOIN FETCH p.user
                LEFT JOIN FETCH r.hospital
                WHERE r.hospital.id = :hospitalId
                """, PatientHospitalRegistration.class)
            .setParameter("hospitalId", hospital.getId())
            .getResultList())
            .isInstanceOf(EntityNotFoundException.class);
    }

    private Patient newPatient(String first, String last, String username) {
        User user = em.persist(User.builder()
            .username(username)
            .passwordHash("h")
            .email(username + "@example.com")
            .phoneNumber("+226" + username)
            .firstName(first)
            .lastName(last)
            .build());

        return Patient.builder()
            .firstName(first)
            .lastName(last)
            .dateOfBirth(LocalDate.of(1990, 1, 1))
            .gender("FEMALE")
            .address("123 Test St")
            .phoneNumberPrimary("+226" + username)
            .email(username + "@example.com")
            .user(user)
            .hospitalId(hospital.getId())
            .organizationId(organization.getId())
            .active(true)
            .build();
    }

    /**
     * Repoints a registration at a patient id that does not exist, which is only
     * possible with referential integrity off — see the class javadoc for why
     * that is the production-accurate configuration rather than a shortcut.
     */
    private void orphanPatientReference(UUID registrationId) {
        EntityManager e = em.getEntityManager();
        e.createNativeQuery("SET REFERENTIAL_INTEGRITY FALSE").executeUpdate();
        e.createNativeQuery(
                "UPDATE clinical.patient_hospital_registrations "
                    + "SET patient_id = :orphan WHERE id = :id")
            .setParameter("orphan", UUID.randomUUID())
            .setParameter("id", registrationId)
            .executeUpdate();
        e.createNativeQuery("SET REFERENTIAL_INTEGRITY TRUE").executeUpdate();
        em.flush();
        em.clear();
    }
}
