-- =============================================================
-- V113: Protect clinical.patients.user_id integrity
--
-- WHY
--   Patient.user is mapped @OneToOne(unique = true) with a named
--   @ForeignKey, but NEITHER constraint exists in the database:
--     * V1__Initial_Schema.sql was generated by Hibernate's
--       SchemaExport, which emits no FOREIGN KEY and no UNIQUE
--       (see the header of V1_1__add_unique_constraints.sql).
--     * V1_1 backfilled unique indexes for security.roles,
--       hospital.organizations and security.users — but not
--       clinical.patients.
--     * prod runs ddl-auto=validate, so Hibernate never enforces it.
--
--   The identical defect on the sibling table caused production
--   "More than one row with the given identifier" failures and was
--   fixed for hospital.staff by V8. clinical.patients was missed.
--
--   Symptom: GET /registrations 500s for every staff user, because
--   the response mapper initialises the LAZY Patient.user proxy and
--   User.patientProfile is forced EAGER by @NotFound, issuing
--   SELECT ... FROM clinical.patients WHERE user_id = ? per row.
--
-- WHAT THIS DOES *NOT* DO
--   It does not delete duplicate patient rows. V8 could safely delete
--   duplicate staff rows; patients cannot be treated the same way.
--   clinical.patients is referenced by appointments, prescriptions,
--   lab results, encounters, registrations and more, and because the
--   schema carries no foreign keys at all, a DELETE here would not
--   fail loudly — it would silently orphan clinical records. Losing
--   clinical data to tidy an index is never the right trade.
--
--   So: on a healthy database this adds the missing unique index. On
--   a database that already contains duplicates it adds a plain index
--   and raises a notice naming the affected user_ids, leaving the rows
--   for a human to reconcile. Either way the migration must not fail
--   the deploy — a failed changeset mid-Liquibase wedges the
--   environment (see the V108 incident).
--
--   The application side is already defensive: the registration mapper
--   catches proxy-initialisation failures per row, so the desk list
--   renders even while duplicates remain.
-- =============================================================

DO $$
DECLARE
    duplicate_count   integer;
    duplicate_users   text;
    orphan_count      integer;
BEGIN
    -- ── 1. Report dangling user_id values (no matching security.users row) ──
    SELECT COUNT(*) INTO orphan_count
    FROM   clinical.patients p
    WHERE  p.user_id IS NOT NULL
      AND  NOT EXISTS (SELECT 1 FROM security.users u WHERE u.id = p.user_id);

    IF orphan_count > 0 THEN
        RAISE NOTICE 'V113: % clinical.patients row(s) reference a non-existent security.users id. '
                     'These render with a null username and are left intact for reconciliation.',
                     orphan_count;
    END IF;

    -- ── 2. Add the unique index only if the data allows it ──
    SELECT COUNT(*) INTO duplicate_count
    FROM  (SELECT user_id
           FROM   clinical.patients
           WHERE  user_id IS NOT NULL
           GROUP  BY user_id
           HAVING COUNT(*) > 1) dupes;

    IF duplicate_count = 0 THEN
        CREATE UNIQUE INDEX IF NOT EXISTS uq_patient_user_id
            ON clinical.patients (user_id);
        RAISE NOTICE 'V113: unique index uq_patient_user_id created.';
    ELSE
        SELECT string_agg(user_id::text, ', ') INTO duplicate_users
        FROM  (SELECT user_id
               FROM   clinical.patients
               WHERE  user_id IS NOT NULL
               GROUP  BY user_id
               HAVING COUNT(*) > 1) dupes;

        RAISE WARNING 'V113: % user_id value(s) have duplicate clinical.patients rows, so the UNIQUE '
                      'index was NOT created. Reconcile these before re-running: %',
                      duplicate_count, duplicate_users;

        -- A plain index still removes the sequential scan that the forced-EAGER
        -- User.patientProfile lookup performs on every row.
        CREATE INDEX IF NOT EXISTS idx_patient_user_id
            ON clinical.patients (user_id);
    END IF;
END $$;
