-- =============================================================
-- V115: Stop clinical.patient_hospital_registrations.patient_id
--       from pointing at patients that do not exist.
--
-- WHY
--   A single registration row whose patient_id had no matching
--   clinical.patients row returned HTTP 500 for the ENTIRE
--   Hospital Registrations desk, for every user with permission
--   to register a patient. PatientHospitalRegistration.patient is
--   mapped @ManyToOne(optional = false) — which promises Hibernate
--   the target row exists — so fetch-joining the orphan raised
--   FetchNotFoundException while assembling the result set rather
--   than yielding null.
--
--   PR #447 made the read survive it: the desk list now projects
--   columns instead of fetching the entity graph, so an orphan
--   lists with null patient details. That fixes the symptom. This
--   fixes the cause — nothing stopped the row being created.
--
--   The schema has NO foreign keys anywhere: V1__Initial_Schema.sql
--   was generated by Hibernate's SchemaExport, which emits none,
--   and prod runs ddl-auto=validate, so Hibernate never adds them.
--   Every @JoinColumn(foreignKey = @ForeignKey(name = "...")) in the
--   model — including fk_phr_patient — names a constraint the
--   database has never had. The H2 test profile DOES create them
--   (ddl-auto: create-drop), which is precisely why no test ever
--   reproduced the outage: the suite enforced an integrity model
--   strictly stronger than production's.
--
-- WHY "ON DELETE CASCADE" IS NOT A BEHAVIOUR CHANGE
--   Patient.hospitalRegistrations is already
--   @OneToMany(cascade = ALL, orphanRemoval = true), so deleting a
--   patient through JPA ALREADY deletes that patient's
--   registrations. CASCADE simply makes the database do what the
--   ORM was doing, which additionally covers the paths the ORM does
--   not see — a psql DELETE, or PatientServiceImpl.deletePatient
--   whose own comment concedes it only clears "non-cascaded child
--   records" it knows about. Those paths are how an orphan gets
--   created in the first place.
--
--   CASCADE also cannot introduce a new failure: unlike RESTRICT it
--   never blocks a delete, so no existing flow can start failing on
--   deploy. That is deliberate — a hardening migration must not be
--   able to wedge a delete path in production.
--
-- WHY "NOT VALID"
--   Postgres NOT VALID skips the check of EXISTING rows while still
--   enforcing the constraint on every INSERT and UPDATE. So this
--   closes the door on new orphans without failing the deploy over
--   the one that is already there, and without deleting clinical
--   data to tidy a constraint (the trade V113 also refused).
--
--   Once the surviving orphan is reconciled, promote the constraint
--   with:
--       ALTER TABLE clinical.patient_hospital_registrations
--           VALIDATE CONSTRAINT fk_phr_patient;
--   Find them first with:
--       SELECT r.id, r.patient_id
--       FROM   clinical.patient_hospital_registrations r
--       WHERE  NOT EXISTS (SELECT 1 FROM clinical.patients p
--                          WHERE p.id = r.patient_id);
--
-- SCOPE
--   patient_id only. hospital_id is left alone on purpose: no
--   orphaned hospital_id was found, hospitals ARE hard-deleted
--   (HospitalServiceImpl.deleteById), and adding a constraint there
--   without first settling what a hospital delete should do to its
--   registrations would be guessing at a data-loss decision.
-- =============================================================

DO $$
DECLARE
    orphan_count integer;
    orphan_ids   text;
BEGIN
    -- ── Report any surviving orphans so they are reconcilable ──
    SELECT COUNT(*), string_agg(r.id::text, ', ')
      INTO orphan_count, orphan_ids
      FROM clinical.patient_hospital_registrations r
     WHERE NOT EXISTS (SELECT 1
                         FROM clinical.patients p
                        WHERE p.id = r.patient_id);

    IF orphan_count > 0 THEN
        RAISE WARNING 'V115: % registration(s) reference a non-existent clinical.patients row. '
                      'The constraint is added NOT VALID so they do not fail this deploy; they '
                      'list with null patient details until reconciled. Registration ids: %',
                      orphan_count, orphan_ids;
    END IF;

    -- ── Add the constraint the JPA mapping has always claimed ──
    IF NOT EXISTS (
        SELECT 1
          FROM pg_constraint c
          JOIN pg_class      t ON t.oid = c.conrelid
          JOIN pg_namespace  n ON n.oid = t.relnamespace
         WHERE c.conname = 'fk_phr_patient'
           AND n.nspname = 'clinical'
           AND t.relname = 'patient_hospital_registrations'
    ) THEN
        ALTER TABLE clinical.patient_hospital_registrations
            ADD CONSTRAINT fk_phr_patient
            FOREIGN KEY (patient_id)
            REFERENCES clinical.patients (id)
            ON DELETE CASCADE
            NOT VALID;

        RAISE NOTICE 'V115: fk_phr_patient added (ON DELETE CASCADE, NOT VALID).';
    ELSE
        RAISE NOTICE 'V115: fk_phr_patient already present — nothing to do.';
    END IF;
END $$;
