-- V147: care-gap worklist + defaulter tracing (Tier 2 item 36).
--
-- WHY: item 35 gave every programme enrolment a next_expected_visit, and an
-- ACTIVE enrolment whose date is in the past IS the care gap. The tasklist's
-- framing holds structurally: a care gap is the same row as a recall with a
-- rule behind it instead of a clinician. So tracing rides the ENTIRE
-- existing recall pipeline - the desk worklist, the notification sweep with
-- its preference/SMS-guard handling, the booking flow - and this migration
-- adds only the link that makes a recall traceable back to the enrolment
-- that generated it.
--
-- The UNIQUE index on (program_enrollment_id, due_date) is the dedupe rule:
-- one tracing recall per missed expected-visit date. Recording a visit
-- advances next_expected_visit, so the next miss is a new date and gets a
-- fresh recall; a recall the desk closed without a visit being recorded is
-- NOT recreated for the same date, so the sweep never fights the desk.
-- Partial (IS NOT NULL) because clinician-created recalls carry no
-- enrolment and must not collide with each other.
--
-- ON DELETE SET NULL: purging an enrolment must not take the recall row
-- with it - the recall is the desk's record that tracing was owed and done.
--
-- Rollback:
--   DROP INDEX scheduling.uq_recall_enrollment_due;
--   ALTER TABLE scheduling.patient_recalls DROP COLUMN program_enrollment_id;
-- =============================================================================

ALTER TABLE scheduling.patient_recalls
    ADD COLUMN IF NOT EXISTS program_enrollment_id UUID;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_recall_program_enrollment'
    ) THEN
        ALTER TABLE scheduling.patient_recalls
            ADD CONSTRAINT fk_recall_program_enrollment
            FOREIGN KEY (program_enrollment_id)
            REFERENCES clinical.program_enrollments (id)
            ON DELETE SET NULL;
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uq_recall_enrollment_due
    ON scheduling.patient_recalls (program_enrollment_id, due_date)
    WHERE program_enrollment_id IS NOT NULL;

COMMENT ON COLUMN scheduling.patient_recalls.program_enrollment_id IS
    'Set when the recall was generated by the care-gap sweep (Tier 2 item '
    '36) from an overdue programme enrolment; NULL for clinician-created '
    'recalls. One recall per (enrolment, due date).';
