package com.example.hms.enums;

public enum AuditEventType {
    // Authentication & session
    LOGIN,
    LOGOUT,
    LOGIN_FAILURE,
    PASSWORD_RESET_REQUEST,
    PASSWORD_RESET_COMPLETE,
    PASSWORD_CHANGED,
    MFA_CHALLENGE,
    MFA_FAILURE,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    SESSION_TERMINATED,

    // User & access administration
    USER_CREATE,
    USER_UPDATE,
    USER_DELETE,
    USER_DISABLE,
    USER_ENABLE,
    USER_BOOTSTRAP,
    ROLE_ASSIGNED,
    ROLE_REVOKED,
    PERMISSION_GRANTED,
    PERMISSION_REVOKED,
    ASSIGNMENT_CONFIRMED,

    // Patient identity & consent
    PATIENT_CREATE,
    PATIENT_UPDATE,
    PATIENT_DELETE,
    PATIENT_ACCESS,
    PATIENT_EXPORT,
    PATIENT_MERGE,
    BREAK_GLASS_ACCESS,
    CONSENT_GRANTED,
    CONSENT_REVOKED,
    CONSENT_UPDATE,
    RECORD_SHARE,

    // Care delivery workflow
    APPOINTMENT_CREATED,
    APPOINTMENT_UPDATED,
    APPOINTMENT_CANCELLED,
    PRESCRIPTION_CREATED,
    PRESCRIPTION_UPDATED,
    PRESCRIPTION_DISCONTINUED,
    LAB_ORDER_CREATED,
    LAB_RESULT_UPDATED,
    LAB_RESULT_RELEASED,
    IMAGING_ORDER_CREATED,
    IMAGING_RESULT_UPDATED,

    // Data operations
    ACCESS,
    DATA_ACCESS,
    DATA_UPDATE,
    DATA_EXPORT,
    DATA_DELETE,
    DATA_IMPORT,
    UPDATE,

    // Billing & finance
    INVOICE_CREATED,
    INVOICE_UPDATED,
    PAYMENT_POSTED,
    REFUND_ISSUED,
    CLAIM_SUBMITTED,

    // Security & platform configuration
    SECURITY_POLICY_UPDATED,
    SECURITY_ALERT_TRIGGERED,
    CONFIGURATION_CHANGED,
    API_KEY_CREATED,
    API_KEY_REVOKED,
    INTEGRATION_CONFIGURED,
    PLATFORM_REGISTRY_UPDATED,

    OTHER
}


