package com.example.hms.enums;

public enum HealthMaintenanceReminderType {
    ANNUAL_PHYSICAL,
    MAMMOGRAM,
    COLONOSCOPY,
    PAP_SMEAR,
    PROSTATE_SCREENING,
    SKIN_CANCER_SCREENING,
    EYE_EXAM,
    DENTAL_CHECKUP,
    FLU_SHOT,
    CHOLESTEROL_SCREENING,
    BLOOD_PRESSURE_CHECK,
    DIABETES_SCREENING,
    BONE_DENSITY_SCAN,
    COLORECTAL_SCREENING,
    LUNG_CANCER_SCREENING,
    OTHER
}
