package com.example.hms.enums;

public enum NewbornFollowUpAction {
    NICU_CONSULT,
    PEDIATRICIAN_NOTIFICATION,
    RESPIRATORY_SUPPORT,
    GLUCOSE_MONITORING,
    THERMAL_SUPPORT,
    SEPSIS_EVALUATION,
    OXYGEN_THERAPY,
    FEEDING_SUPPORT,
    MONITORING_RECHECK,
    PARENT_EDUCATION_REINFORCEMENT
}
