package com.example.hms.enums;

/**
 * Education topics recommended for immediate postpartum discharge instructions.
 */
public enum PostpartumEducationTopic {
    WARNING_SIGNS_FEVER,
    WARNING_SIGNS_LOCHIA_ODOR,
    WARNING_SIGNS_PERSISTENT_PAIN,
    WARNING_SIGNS_URINARY_URGENCY,
    WARNING_SIGNS_LEG_SWELLING,
    BREAST_CARE_LACTATION,
    BREAST_ENGORGEMENT_RELIEF,
    PERINEAL_HYGIENE,
    UTERINE_INVOLUTION,
    CONTRACEPTION_OPTIONS,
    RESUMPTION_OF_SEXUAL_ACTIVITY,
    POSTPARTUM_DEPRESSION_SIGNS,
    BOWEL_AND_BLADDER_SELF_CARE,
    SUPPORT_RESOURCES
}
