package com.example.hms.enums;

/** Where a recall row came from (P3 #22). */
public enum RecallSource {
    /** The checkout follow-up request — captured since MVP 6, dropped until V128. */
    CHECKOUT,
    MANUAL,
    /** Generated by the care-gap sweep from an overdue programme enrolment (Tier 2 item 36). */
    PROGRAM_RULE
}
